name: Example usage

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Start Deployment
      uses: gonzalochief/docker-deployment-action@master
      with:
        remote_docker_host: ${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.PUBLIC_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: /root/deployment-test
        stack_file_name: docker-compose.yml
        pull_images_first: true
        keep_files: 3
        args: -p test up -d

    - name: Start Deployment without copy
      uses: gonzalochief/docker-deployment-action@master
      with:
        remote_docker_host: ${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.PUBLIC_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: false
        deploy_path: /root/deployment-test
        stack_file_name: docker-compose.yml
        pull_images_first: true
        keep_files: 3
        args: -p test up -d
